# SPDX-FileCopyrightText: 2026 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

cargo-features = ["profile-rustflags", "panic-immediate-abort"]

[workspace]
resolver = "3"
members = ["crates/malware", "crates/server"]

[profile.small-size]
inherits = "release"
strip = true
opt-level = "z"
codegen-units = 1
lto = true
panic = "immediate-abort"
rustflags = ["-Zlocation-detail=none", "-Zfmt-debug=none"]
