# SPDX-FileCopyrightText: 2026 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "sayware-server"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[[bin]]
name = "sayware-server"
path = "./src/main.rs"

[dependencies]
poem = { version = "=3.1.12", features = ["rustls"] }
poem-openapi = { version = "=5.1.16" }
tokio = { version = "=1.52.1", features = ["rt-multi-thread", "macros"] }
cliclack = { version = "=0.5.4" }
color-eyre = { version = "=0.6.5" }
tracing = { version = "=0.1.44" }
tracing-subscriber = { version = "=0.3.23", default-features = false, features = [
  "fmt",
  "ansi",
  "std",
  "smallvec",
] }
